# Generated by Django 4.0.6 on 2022-08-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista',
            name='clas',
            field=models.CharField(choices=[('Filme', 'Filme'), ('Anime', 'Anime'), ('Série', 'Série')], default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lista',
            name='assistido',
            field=models.CharField(choices=[('Assistindo', 'Assistindo'), ('Assistido', 'Assistido'), ('A Assistir', 'A Assistir')], max_length=10),
        ),
    ]
