# Generated by Django 4.0.6 on 2022-08-05 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_lista_clas_alter_lista_assistido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lista',
            old_name='clas',
            new_name='tipo',
        ),
    ]
