# Generated by Django 4.0.6 on 2022-08-05 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_rename_clas_lista_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lista',
            old_name='assistido',
            new_name='status',
        ),
    ]
