# Generated by Django 4.0.6 on 2022-08-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0008_alter_lista_status_alter_lista_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='status',
            field=models.CharField(blank=True, choices=[('Assistindo', 'Assistindo'), ('Assistido', 'Assistido'), ('A Assistir', 'A Assistir')], max_length=10, null=True),
        ),
    ]
