# Generated by Django 4.0.6 on 2022-08-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0009_alter_lista_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='status',
            field=models.CharField(blank=True, choices=[('Assistindo', 'Assistindo'), ('Assistido', 'Assistido'), ('A Assistir', 'A Assistir')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
