# Generated by Django 4.0.6 on 2022-08-01 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0005_entrada_alter_transacao_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrada',
            options={'verbose_name_plural': 'Entradas'},
        ),
        migrations.AlterModelOptions(
            name='transacao',
            options={'verbose_name_plural': 'Entradas'},
        ),
    ]
