# Generated by Django 4.0.6 on 2022-08-02 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0006_alter_entrada_options_alter_transacao_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transacao',
            options={'verbose_name_plural': 'Transações'},
        ),
    ]
