# Generated by Django 4.0.6 on 2022-08-02 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0007_alter_transacao_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
